/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  NewAccount: () => import('#controllers/new_account_controller'),
  PasswordReset: () => import('#controllers/password_reset_controller'),
  Session: () => import('#controllers/session_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  AdminDashboard: () => import('#controllers/admin_dashboard_controller'),
}
