/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['id', 'email', 'token', 'expiresAt', 'createdAt'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare email: string
  @column()
  declare token: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class RoleSchema extends BaseModel {
  static $columns = ['id', 'name', 'createdAt'] as const
  $columns = RoleSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullName', 'email', 'password', 'roleId', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string | null
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare roleId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
